wait for previous requests to complete
nwisbeta/api-catalogue pull request #32
Opened 2020-08-13 14:36 UTC by velsietis

Starting to feel a little over-engineered but it works.

2020-08-13 15:15 UTC, BobbyCGD requested changes

2020-08-13 15:15 UTC, BobbyCGD commented on .github/actions/api-catalogue-processor/deploy-to-azure-apim.js
> +    const statusChecks = {}
Shouldn't we loop through all statusChecks at the end to record the outcome after APIM processes the request?

2020-08-13 16:06 UTC, velsietis commented on .github/actions/api-catalogue-processor/deploy-to-azure-apim.js
> +    const statusChecks = {}
I've pushed a new change for this.

2020-08-14 10:22 UTC, BobbyCGD approved these changes

2020-08-14 10:22 UTC, merged